tool  prepartaing data it used to perform math operation
handling  dimensional array
binding to other library
list as less library  than numpy

In [1]:
import numpy as np

In [5]:
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [2]:
data=[1,2,3]
data


[1, 2, 3]

In [3]:
type(data)

list

In [4]:
arr=np.array(data)

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr=np.array([1,5,8,69])#prefered one

In [7]:
arr

array([ 1,  5,  8, 69])

In [8]:
type(arr)

numpy.ndarray

# Arange

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(start=10,stop=20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(start=10,stop=20)

array([10, 12, 14, 16, 18])

In [14]:
np.arange(start=10,stop=2.5)

array([], dtype=float64)

In [15]:
np.arange(start=10,stop=20,dtype=float)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

# Zeros& ones

In [16]:
np.zeros(shape=3)

array([0., 0., 0.])

In [17]:
np.ones(shape=3)

array([1., 1., 1.])

In [18]:
np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.zeros(shape=(3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Linspace

In [22]:
#leanearily spaced
np.linspace(start=0,stop=20,num=5)

array([ 0.,  5., 10., 15., 20.])

In [24]:
# eye

In [23]:
#diagonal matrix
np.eye(N=3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

# random

In [29]:
np.random.rand(2)#0-1

array([0.70340309, 0.24642232])

In [32]:
np.random.rand(3,9)

array([[0.26059926, 0.4005732 , 0.65826566, 0.03941192, 0.80578859,
        0.14285224, 0.14077888, 0.71544146, 0.72151784],
       [0.58920234, 0.70904056, 0.25801788, 0.27435544, 0.33985243,
        0.28612893, 0.47161735, 0.92099748, 0.09693946],
       [0.0368052 , 0.96445905, 0.63198669, 0.00944155, 0.55650439,
        0.36104342, 0.07254812, 0.48208539, 0.74875488]])

In [33]:
np.random.randn(3,9)#-1 to 1

array([[ 1.19820048, -0.42270381, -1.1723668 , -0.96155533, -0.39210558,
        -1.1271699 ,  3.65401604, -0.21324627, -1.05753335],
       [ 0.80027961,  1.21215605,  0.99487013,  0.01082012,  2.35220297,
        -0.81319342, -0.09307401,  1.25242626,  1.35895374],
       [-1.04200694,  0.71009129,  0.75637246, -0.41901563, -0.32461637,
         1.49455866, -1.86741511,  0.61547426, -1.1660358 ]])

In [34]:
np.random.randint(2)

1

In [36]:
np.random.rand(10,25)

array([[0.10288491, 0.17283847, 0.01975429, 0.6756223 , 0.1093649 ,
        0.89682192, 0.44570745, 0.30899118, 0.60881794, 0.93551486,
        0.69784442, 0.39372657, 0.5067824 , 0.98384875, 0.09391894,
        0.00648868, 0.48497432, 0.10486164, 0.96297833, 0.19654026,
        0.37441758, 0.01331501, 0.87470451, 0.86429447, 0.34052181],
       [0.3022155 , 0.92866497, 0.565373  , 0.88940599, 0.93659776,
        0.6712694 , 0.5123315 , 0.55211043, 0.52323083, 0.22427472,
        0.42338938, 0.29506314, 0.51379099, 0.32618621, 0.30939042,
        0.41651839, 0.30371378, 0.37426297, 0.29596079, 0.7354718 ,
        0.89750461, 0.83327082, 0.15099849, 0.73963902, 0.71618824],
       [0.79403374, 0.96636816, 0.92817534, 0.68652355, 0.74262124,
        0.67190326, 0.84130927, 0.09808558, 0.81997037, 0.81919187,
        0.80111534, 0.07623091, 0.40993077, 0.35610777, 0.22458945,
        0.07900892, 0.04006159, 0.12908011, 0.68794303, 0.0646262 ,
        0.60665889, 0.41103614, 0.73632617, 0.

# Array attribute and method

In [37]:
arr=np.arange(25)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
arr.shape

(25,)

In [44]:
arr.reshape(5,5)
arr



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
arr.shape

(1, 25)

In [45]:
arr= arr.reshape(1,25)

In [46]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [49]:
arr=arr.arange(1,25)

AttributeError: 'numpy.ndarray' object has no attribute 'arange'

In [50]:
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]]


In [51]:
matrix=[[0,1,2],[5,8,9],[5,6,8]]

In [56]:
matrix

[[0, 1, 2], [5, 8, 9], [5, 6, 8]]

In [59]:
arr.dtype


dtype('int32')

# indexing

In [61]:
arr=np.arange(0,11)

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr[0]

0

In [64]:
arr[-1]

10

In [65]:
arr[:5]

array([0, 1, 2, 3, 4])

In [66]:
arr[:-4]

array([0, 1, 2, 3, 4, 5, 6])

In [67]:
arr[0:5]=10

In [68]:
arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [69]:
arr=np.arange(0,11)

In [70]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
newarr=arr[0:6]

In [72]:
newarr

array([0, 1, 2, 3, 4, 5])

In [7]:
arr=[[0,1,2],[5,8,9],[5,6,8]]

In [9]:
arr

[[0, 1, 2], [5, 8, 9], [5, 6, 8]]

In [10]:
arr=np.array([0,1,2],[5,8,9],[5,6,8])

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [77]:
arr[:,-1]

TypeError: list indices must be integers or slices, not tuple

In [80]:
arr=np.arange(0,11)

In [81]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

# arthimatic operation

In [83]:
arr=np.arange(0,10)

In [84]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [86]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [87]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [88]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [89]:
arr/arr

<ipython-input-89-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

# univesal array function

In [90]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [91]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [92]:
np.max(arr)

9

In [94]:
np.min(arr)

0

In [96]:
np.log(arr)

<ipython-input-96-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

# append,concatenate and stack 

In [99]:
arr=np.array([[0,2,3],[3,6,8],[6,3,7]])

In [100]:
arr

array([[0, 2, 3],
       [3, 6, 8],
       [6, 3, 7]])

In [101]:
arr1=np.array([[0,2,3],[3,6,8]])

In [102]:
arr1

array([[0, 2, 3],
       [3, 6, 8]])

In [103]:
arr1.shape

(2, 3)

In [104]:
arr.shape

(3, 3)

In [109]:
np.append(arr=arr,values=arr1,axis=0)

array([[0, 2, 3],
       [3, 6, 8],
       [6, 3, 7],
       [0, 2, 3],
       [3, 6, 8]])

In [111]:
np.append(arr=arr,values=arr,axis=1)

array([[0, 2, 3, 0, 2, 3],
       [3, 6, 8, 3, 6, 8],
       [6, 3, 7, 6, 3, 7]])

In [116]:
np.concatenate((arr,arr1),axis=0)#0=rows  1=columns

array([[0, 2, 3],
       [3, 6, 8],
       [6, 3, 7],
       [0, 2, 3],
       [3, 6, 8]])

In [117]:
np.vstack((arr,arr1))

array([[0, 2, 3],
       [3, 6, 8],
       [6, 3, 7],
       [0, 2, 3],
       [3, 6, 8]])

In [122]:
np.hstack(arr)

array([0, 2, 3, 3, 6, 8, 6, 3, 7])